image: maven:3.6.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B verify --file pom.xml
          - pipe: atlassian/checkstyle-report:0.3.0
          - pipe: atlassian/git-secrets-scan:0.5.1

    - step:
        name: Package Maven Project
        script:
          - mvn package
        artifacts:
          - target/springboot-thymeleaf-crud-web-app-0.0.1-SNAPSHOT.jar

    - step:
        name: Deploy to Heroku
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: target/springboot-thymeleaf-crud-web-app-0.0.1-SNAPSHOT.jar